### PR TITLE
change fileName whitelist -> allowList & blacklist -> blockList

### PR DESCRIPTION
**Pull request by abhishekpatel946**
Changed in fileName according to avoid offense

> Renamed blacklist.txt and whitelist.txt to blockList.txt and allowList.txt
> Also edited the script to update references following the rename (above)

### CODE REVIEW

**Comment by abhishekpatel946** [comment]
Shall it work? I'll be changed name according to camelCase .

**Comment by joncojonathan** [comment]
I've just noted that line 40 of `script/PSLogonFailures.ps1` already declares a variable called `$blocklist` which the renamed file path variable (on line 31) will collide with.  Suggest changing the file path variables to be called `$allowListFile` and `$blockListFile`.

**Comment by abhishekpatel946** [comment]
replaced  `$blocklist` with `$blockList`  and `$whitelist` with `$allowList`  in `script/PSLogonFailures.ps1`

**Comment by joncojonathan** [comment]
Thanks for your contribution @abhishekpatel946, I've marked this as accepted for Hacktoberfest.  There were two PRs for this issue so I'm closing this one.

**Pull request closed without merging**
